### PR TITLE
global css, and awesome font implementation

### PR DESCRIPTION
**Pull request by kianMIC**
Implemented the awesome font library to add icons and make it more friendly to the eye, as well as adding the latest general css styles, so that it is more coupled to the final version.
#24

### CODE REVIEW

**Review by Albamph — APPROVED** [review]
Nice!

**Review by AlexFlFe — APPROVED** [review]
LGTM

**Review by AleXKiD31 — APPROVED** [review]
Looks good to me.
Se ve bien para mi.
Ça me semble bien.

**Review by JordiJT99 — APPROVED** [review]

**Review by SaraVictorFernandez — APPROVED** [review]
lgtm

**Pull request merged**
